### ISSUE TITLE
Checklist for disabling Travis

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#106]
Needed before we can turn off Travis:

 - [x] Build for Android in GitHub Actions
 - [x] Run integration tests
     - Apparently aw-client-rust has some built-in, and it starts the server itself.
 - [ ] Run tests with coverage and report
     - Coverage is kinda broken anyway, so not the end of the world if we delay it.
